# Generated by Django 3.2.6 on 2021-09-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210902_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='domain_roles',
            new_name='domain_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resource_permissions',
        ),
    ]
